# Generated by Django 5.1.1 on 2025-12-31 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0014_alter_rank_rank_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoorEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_time', models.DateTimeField()),
                ('event_type', models.CharField(choices=[('OPENED', 'Door Opened'), ('CLOSED', 'Door Closed')], max_length=6)),
                ('notes', models.JSONField()),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.member')),
                ('previous_event', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_event', to='door.doorevent')),
            ],
        ),
    ]
