# Generated by Django 5.1.1 on 2025-12-31 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('door', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doorevent',
            name='notes',
            field=models.JSONField(default=dict),
        ),
    ]
