# Generated by Django 5.1.1 on 2025-05-13 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_alter_financerecord_resolved'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='payment_method',
            field=models.CharField(choices=[('NONE', '-'), ('CASH', 'Cash'), ('CARD', 'Card'), ('TFER', 'Bank Transfer')], default='NONE', max_length=5),
        ),
    ]
