# Generated by Django 5.1.1 on 2025-09-02 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_membership_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rank',
            name='rank_name',
            field=models.TextField(choices=[('EXCLUDED', 'Excluded'), ('GATEKEEPER', 'Gatekeeper'), ('WEBKEEPER', 'Webkeeper'), ('COMMITTEE', 'Committee'), ('LIFEMEMBER', 'Life Member'), ('PRESIDENT', 'President'), ('VICEPRESIDENT', 'Vice-President'), ('TREASURER', 'Treasurer'), ('SECRETARY', 'Secretary'), ('LIBRARIAN', 'Librarian'), ('FRESHERREP', 'Fresher-Rep'), ('OCM', 'OCM'), ('IPP', 'IPP (Immediate Past President)'), ('SUPERUSER', 'Superuser Mode Active')], max_length=20),
        ),
    ]
